# SPDX-FileCopyrightText: The gigtag authors
# SPDX-License-Identifier: CC0-1.0

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-case-conflict
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: forbid-new-submodules
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.22.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.17.2
    hooks:
      - id: markdownlint-cli2
        exclude: ^LICENSE\.md$
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        args: [--ignore-words=.codespellignore]
  - repo: https://github.com/sirosen/check-jsonschema
    rev: 0.31.3
    hooks:
      - id: check-github-actions
      - id: check-github-workflows
  # Markdown
  # TODO: Remove unmaintained Prettier plugin.
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        types_or:
          - markdown
  # YAML
  - repo: https://github.com/google/yamlfmt
    rev: v0.16.0
    hooks:
      - id: yamlfmt
  # TOML
  - repo: https://github.com/ComPWA/taplo-pre-commit
    rev: v0.9.3
    hooks:
      - id: taplo-format
      - id: taplo-lint
  # Licensing: https://reuse.software
  - repo: https://github.com/fsfe/reuse-tool
    rev: v5.0.2
    hooks:
      - id: reuse
  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
      - id: fmt
        args: [--all, --]
      - id: clippy
        args: [--locked, --workspace, --all-targets, --, -D, warnings]
      - id: clippy
        name: clippy (all-features)
        args: [--locked, --workspace, --all-features, --all-targets, --, -D, warnings]
  - repo: local
    hooks:
      - id: cargo-doc
        name: cargo-doc
        entry: env RUSTDOCFLAGS=-Dwarnings cargo
        language: system
        pass_filenames: false
        args: [doc, --locked, --workspace, --no-deps]
