# SPDX-FileCopyrightText: The gigtag authors
# SPDX-License-Identifier: MPL-2.0

[package]
name = "gigtag"
description = "A lightweight, textual tagging system for DJs."
version = "0.1.7"
license = "MPL-2.0"
readme = "README.md"
repository = "https://github.com/uklotzde/gigtag"
keywords = ["music", "dj", "metadata", "tagging"]
categories = ["parser-implementations"]
edition = "2021"
include = ["/src", "/README.md", "/LICENSES"]
rust = "1.70"

[dependencies]
anyhow = "1.0.75"
compact_str = "0.7.1"
itertools = "0.11.0"
percent-encoding = "2.3.0"
regex = "1.10.1"
time = { version = "0.3.30", features = ["formatting", "macros", "parsing"] }
thiserror = "1.0.49"
url = "2.4.1"

[features]
default = []
