# SPDX-FileCopyrightText: The gigtag authors
# SPDX-License-Identifier: MPL-2.0

[package]
name = "gigtag"
description = "A lightweight, textual tagging system for DJs."
version = "0.1.5"
license = "MPL-2.0"
readme = "README.md"
repository = "https://github.com/uklotzde/gigtag"
keywords = ["music", "dj", "metadata", "tagging"]
categories = ["parser-implementations"]
edition = "2021"

[dependencies]
anyhow = "1.0.69"
compact_str = "0.7.0"
itertools = "0.10.5"
once_cell = "1.17.1"
percent-encoding = "2.2.0"
regex = "1.7.1"
time = { version = "0.3.19", features = ["formatting", "macros", "parsing"] }
thiserror = "1.0.38"
url = "2.3.1"

[features]
default = []
