# SPDX-FileCopyrightText: The gigtags authors
# SPDX-License-Identifier: MPL-2.0

[package]
name = "gigtags"
description = "A lightweight, textual tagging system for DJs."
version = "0.0.13"
license = "MPL-2.0"
readme = "README.md"
repository = "https://github.com/uklotzde/gigtags"
keywords = ["music", "dj", "metadata", "tagging"]
categories = ["parser-implementations"]
edition = "2021"

[dependencies]
anyhow = "1.0"
compact_str = "0.5"
itertools = "0.10"
once_cell = "1.13"
percent-encoding = "2.1"
regex = "1.6"
time = { version = "0.3", features = ["formatting", "macros", "parsing"] }
thiserror = "1.0"
url = "2.2"

[features]
default = []
