# SPDX-FileCopyrightText: The gigtag authors
# SPDX-License-Identifier: CC0-1.0

# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: pre-commit

permissions:
  contents: read

on:
  pull_request:
  push:
    branches:
      - "*"
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Generate Cargo.lock
        run: cargo generate-lockfile

      - name: Cache Rust toolchain and build artifacts
        uses: Swatinem/rust-cache@v2
        with:
          # Distinguished by the action name to avoid sharing between different actions.
          shared-key: pre-commit

      - name: Detect code style issues
        uses: pre-commit/action@v3.0.0
